version: "3.9"
networks:
  internal:

services:
  proxy:
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
     # - "./frontend:/www/frontend"
    networks:
      internal:

  simple-jwt-provider:
    image: leberkleber/simple-jwt-provider:v1.1.0
    restart: on-failure
    environment:
      SJP_SERVER_ADDRESS: ":8080"
      SJP_JWT_PRIVATE_KEY: "\n-----BEGIN EC PRIVATE KEY-----\nMIHcAgEBBEIASzDZeTVLxcE5KTAmwrKwFjzr5cDrA+tttx9XRUz0K7AlROtj7cMG\nrHu/bdKj7lc2WaW8x/EOrU/FeCcsIL5nTH+gBwYFK4EEACOhgYkDgYYABAFBJr90\nWldGrPppBCbHqw2nGXeafxnSj6qB+A7E8A/G74mmmwIaqtf/pJ5QjqTPcAVUAEYF\nTz/0SPO3tPL1Ym3V0QH7TfnTf7EueabJqPdsSGR6uvbb2YOA9vy4OU8SXp/9a/4x\nr94giWgKjxYkB7xiy+IiZsWEBXU0rz7rb+IwJ82PfQ==\n-----END EC PRIVATE KEY-----"
      SJP_DB_HOST: "db"
      SJP_DB_PORT: 5432
      SJP_DB_NAME: "simple-jwt-provider"
      SJP_DB_USERNAME: "postgres"
      SJP_DB_PASSWORD: "postgres"
      SJP_ADMIN_API_ENABLE: "true"
      SJP_ADMIN_API_USERNAME: "username"
      SJP_ADMIN_API_PASSWORD: "password"
      SJP_MAIL_SMTP_HOST: "smtp"
      SJP_MAIL_SMTP_PORT: 1025
      SJP_MAIL_SMTP_PASSWORD: ""
      SJP_MAIL_SMTP_USERNAME: ""
      SJP_MAIL_TLS_INSECURE_SKIP_VERIFY: "true"
      SJP_MAIL_TLS_SERVER_NAME: "smtp"
    networks:
      internal:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "simple-jwt-provider"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      internal:

  smtp:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
    networks:
      internal: